id: P77BB7D38
initial_creation_type: ocr
source_metadata:
  volumes:
    641bd813f24344ae82b4a345c139acb2:
      base_file: v065.txt
      image_group_id: I1PD95910
      title: ཚིགས་སུ་བཅད་པ་གཅིག་པའི་བཤད་པ།
      total_pages: 1498
      volume_number: 65
